<script setup>
/**
 * BrandForm.vue — Shared create/edit form for the Brand resource
 *
 * Used by both Create.vue (:brand="null", method="post")
 * and Edit.vue (:brand="existingRecord", method="put").
 *
 * WHY one form component for both create and edit?
 *  - Both forms have identical fields. Sharing avoids duplicating template, validation
 *    display, image preview logic, and submission handling.
 *  - The only differences (submit URL, HTTP method, initial values) are passed as props.
 */
import { watch, computed, ref } from 'vue';
import { useForm } from '@inertiajs/vue3';
import { useToast } from 'primevue/usetoast';

import InputText from 'primevue/inputtext';
import Button from 'primevue/button';
import InputSwitch from 'primevue/inputswitch';
import FileUpload from 'primevue/fileupload';

const toast = useToast();

const props = defineProps({
    // null on Create, existing BrandResource array on Edit
    brand: { type: Object, default: null },

    // Full URL of the route to submit to (generated by route() in the parent)
    submitUrl: { type: String, required: true },

    // 'post' for create, 'put' for edit
    method: { type: String, required: true },
});

// ─── Inertia Form ─────────────────────────────────────────────────────────────
/**
 * useForm() creates a reactive form object that:
 *  - Tracks field values (v-model targets)
 *  - Collects server validation errors into form.errors after a failed submission
 *  - Exposes form.processing (true while the XHR is in-flight — disables the button)
 *  - Serialises everything to FormData automatically when forceFormData is set
 *
 * WHY _method: 'put' inside the form?
 *  - Browsers cannot send PUT/PATCH with a file in FormData. The workaround is to
 *    POST with a hidden `_method=put` field. Laravel reads this and routes it as PUT.
 *    This is called "method spoofing" — it's a standard Laravel pattern.
 */
const form = useForm({
    name: '',
    image: null, // holds the File object when the user picks a logo
    status: true, // defaults to active for new brands
    _method: props.method === 'put' ? 'put' : 'post',
});

// UI-only label: "Created" after store, "Updated" after update — never sent to server
const methodText = computed(() => (props.method === 'put' ? 'Updated' : 'Created'));

// Holds the current image preview URL (existing logo URL on Edit, blob: URL after new pick)
const preview = ref(null);

// ─── Prefill on Edit ──────────────────────────────────────────────────────────
/**
 * WHY watch with { immediate: true }?
 *  - On Edit, `brand` is already set when the component mounts. Without `immediate`,
 *    the watch only fires on CHANGES — the initial value would be missed.
 *  - On Create, brand is null so the if block is skipped — form stays blank.
 */
watch(
    () => props.brand,
    (brand) => {
        if (brand) {
            form.name = brand.name;
            form.status = Boolean(brand.status); // ensure true/false, not 1/0
            preview.value = brand.image; // full URL from BrandResource
        }
    },
    { immediate: true },
);

// ─── Image Selection ──────────────────────────────────────────────────────────
/**
 * Called when the user picks a file via PrimeVue's FileUpload component.
 *
 * WHY URL.createObjectURL()?
 *  - Creates a temporary browser-local blob: URL for the selected File so we can
 *    show a preview <img> without uploading yet. The blob URL is released on page unload.
 */
const onImageSelect = (event) => {
    const file = event.files[0];
    form.image = file; // store File object in form for multipart upload
    preview.value = URL.createObjectURL(file); // blob: URL for the preview <img>
};

// ─── Submit ───────────────────────────────────────────────────────────────────
/**
 * WHY form.post() even for the edit form (method="put")?
 *  - Browsers cannot send a file via PUT in FormData. We always POST and rely on
 *    `_method: 'put'` in the body for Laravel method spoofing.
 *
 * forceFormData: true → always serialise as FormData (even without a file).
 *   Without this, Inertia sends JSON for non-file forms — inconsistent behaviour.
 *
 * preserveScroll: true → page stays at current scroll position after redirect.
 */
const submit = () => {
    form.post(props.submitUrl, {
        forceFormData: true,
        preserveScroll: true,
        onSuccess: () => {
            toast.add({
                severity: 'success',
                summary: methodText.value,
                detail: `Brand ${methodText.value.toLowerCase()} successfully.`,
                life: 3000,
            });
        },
        onError: () => {
            toast.add({
                severity: 'error',
                summary: 'Validation Error',
                detail: 'Please check the form fields and try again.',
                life: 5000,
            });
        },
    });
};
</script>

<template>
    <div class="card bg-white dark:bg-gray-800 p-6 rounded-lg shadow">
        <!-- Name — required, drives Spatie HasSlug auto-generation on the server -->
        <div class="mb-4">
            <label class="block mb-2 font-medium text-gray-700 dark:text-gray-200">Name</label>

            <!--
                v-model="form.name" — two-way binding: updates form.name on every keystroke.
                form.errors.name is populated by Inertia after a failed server validation.
            -->
            <InputText v-model="form.name" class="w-full" placeholder="e.g. Nike" />
            <small v-if="form.errors.name" class="text-red-500 mt-1 block">
                {{ form.errors.name }}
            </small>
        </div>

        <!-- Brand logo with live preview -->
        <div class="mb-4">
            <label class="block mb-2 font-medium text-gray-700 dark:text-gray-200">Logo</label>

            <!--
                FileUpload (mode="basic") renders a single "Choose Image" button.
                :auto="false" → does NOT upload immediately — we upload with the form submit.
                accept="image/*" → browser file picker filter (server validates MIME type too).
                @select="onImageSelect" → stores the File and creates a preview blob: URL.
            -->
            <FileUpload
                mode="basic"
                accept="image/*"
                :auto="false"
                choose-label="Choose Logo"
                @select="onImageSelect"
            />

            <!--
                v-if="preview" — only show the preview img when a URL exists.
                On Create: null until the user picks a file.
                On Edit: starts as the existing logo URL from BrandResource.
            -->
            <div v-if="preview" class="mt-3">
                <img
                    :src="preview"
                    class="h-24 rounded shadow object-contain"
                    alt="Brand logo preview"
                />
            </div>

            <small v-if="form.errors.image" class="text-red-500 mt-1 block">
                {{ form.errors.image }}
            </small>
        </div>

        <!-- Status toggle — active brand is visible on storefront, inactive is hidden -->
        <div class="mb-6 flex items-center gap-3">
            <!--
                InputSwitch is PrimeVue's toggle switch — binds to a boolean.
                v-model="form.status" sends 1 (true) or 0 (false) to Laravel.
                Laravel's `boolean` validation rule accepts true/false/1/0.
            -->
            <InputSwitch v-model="form.status" />
            <span class="text-gray-700 dark:text-gray-200">Active</span>
        </div>

        <!--
            :loading="form.processing" disables the button and shows a spinner while
            the XHR is in-flight — prevents duplicate submissions on slow connections.
        -->
        <Button label="Save Brand" icon="pi pi-check" :loading="form.processing" @click="submit" />
    </div>
</template>
