<script setup>
/**
 * CategoryForm.vue — Shared create/edit form for the Category resource
 *
 * Used by both Create.vue (:category="null", method="post")
 * and Edit.vue (:category="existingRecord", method="put").
 *
 * WHY one form component for both create and edit?
 *  - Both forms have identical fields. Sharing avoids duplicating template, validation
 *    display, image preview logic, and submission handling.
 *  - The only differences (submit URL, HTTP method, initial values) are passed as props.
 */
import { watch, computed } from 'vue';
import { useForm } from '@inertiajs/vue3';

// PrimeVue form components
import InputText from 'primevue/inputtext';
import Textarea from 'primevue/textarea';
import Button from 'primevue/button';
import InputSwitch from 'primevue/inputswitch';
import FileUpload from 'primevue/fileupload';

// useToast: accesses the Toast service registered in app.js.
// Calling toast.add() pushes a notification into the <Toast> outlet in AuthenticatedLayout.
import { useToast } from 'primevue/usetoast';

// ref: wraps a primitive/object so Vue can track changes and re-render.
import { ref } from 'vue';

const toast = useToast();

const props = defineProps({
    // null on Create, existing CategoryResource array on Edit
    category: { type: Object, default: null },

    // Full URL of the route to submit to (generated by route() in the parent)
    submitUrl: { type: String, required: true },

    // 'post' for create, 'put' for edit
    method: { type: String, required: true },
});

// ─── Inertia Form ────────────────────────────────────────────────────────────
/**
 * useForm() creates a reactive form object that:
 *  - Tracks field values (v-model targets)
 *  - Collects server validation errors into form.errors
 *  - Exposes form.processing (true while the XHR is in-flight — used to disable the button)
 *  - Serialises everything to FormData automatically when forceFormData is set
 *
 * WHY _method: 'put' inside the form?
 *  - Browsers can't send PUT requests with a file (FormData). The workaround is to
 *    POST with a hidden `_method=put` field. Laravel reads this and routes it as PUT.
 *    This is called "method spoofing" — it's a standard Laravel pattern.
 *
 * WHY NOT store `methodText` in useForm?
 *  - Every key in useForm() is sent to the server as POST body data. `methodText` is
 *    a UI-only label ("Created" / "Updated") — it should never reach the server.
 *    Use computed() for UI-only derived values.
 */
const form = useForm({
    name:        '',
    description: '',
    image:       null,   // holds the File object when the user picks an image
    status:      true,   // defaults to active for new categories
    _method:     props.method === 'put' ? 'put' : 'post', // Laravel method spoofing
});

// UI-only label: "Created" after store, "Updated" after update — never sent to server
const methodText = computed(() => props.method === 'put' ? 'Updated' : 'Created');

// Holds the URL for the image preview (either the existing image URL or a blob: URL)
const preview = ref(null);

// ─── Prefill on Edit ─────────────────────────────────────────────────────────
/**
 * Watch the `category` prop and populate the form when it's available.
 *
 * WHY watch with { immediate: true }?
 *  - On Edit, `category` is already set when the component mounts. Without `immediate`,
 *    the watch callback only fires on CHANGES — we'd miss the initial value.
 *  - On Create, category is null so the if block is skipped — form stays empty.
 *
 * WHY watch the prop instead of setting values in setup() directly?
 *  - Props may not be available synchronously during SSR or async page resolution.
 *    Watching is the safe, reactive way to respond to prop availability.
 */
watch(
    () => props.category,
    (category) => {
        if (category) {
            form.name        = category.name;
            form.description = category.description;
            form.status      = Boolean(category.status); // ensure true/false, not 1/0
            preview.value    = category.image;           // full URL from CategoryResource
        }
    },
    { immediate: true }, // run immediately on mount, not just on future changes
);

// ─── Image Selection ─────────────────────────────────────────────────────────
/**
 * Called when the user picks a file via PrimeVue's FileUpload.
 *
 * WHY URL.createObjectURL()?
 *  - Creates a temporary browser-local URL for the selected File object so we can
 *    show a preview <img> without uploading the file yet.
 *  - The blob: URL is revoked by the browser when the page unloads — no memory leak.
 */
const onImageSelect = (event) => {
    const file = event.files[0];
    form.image = file;                           // store File object in form for upload
    preview.value = URL.createObjectURL(file);   // generate blob: URL for <img> preview
};

// ─── Submit ──────────────────────────────────────────────────────────────────
/**
 * WHY form.post() instead of form.put() for the edit form?
 *  - Browsers cannot send a multipart/form-data body (needed for file uploads) via PUT.
 *    We always POST, and rely on `_method: 'put'` in the form body for Laravel spoofing.
 *
 * forceFormData: true → always serialise as FormData, even when there's no file.
 *   Without this, Inertia sends JSON for non-file forms and FormData only when a
 *   File is present — inconsistent. With it, Laravel always receives FormData.
 *
 * preserveScroll: true → page stays at current scroll position after redirect.
 *   Useful on forms that are lower on the page.
 */
const submit = () => {
    form.post(props.submitUrl, {
        forceFormData: true,
        preserveScroll: true,
        onSuccess: () => {
            toast.add({
                severity: 'success',
                summary: methodText.value,
                detail: `Category ${methodText.value.toLowerCase()} successfully.`,
                life: 3000,
            });
        },
        onError: () => {
            toast.add({
                severity: 'error',
                summary: 'Error',
                detail: `Failed to save category. Please check the form.`,
                life: 5000,
            });
        },
    });
};
</script>

<template>
<div class="card bg-white dark:bg-gray-800 p-6 rounded-lg shadow">

    <!-- Name field — required, drives the auto-generated slug via Spatie HasSlug -->
    <div class="mb-4">
        <label class="block mb-2 font-medium text-gray-700 dark:text-gray-200">Name</label>

        <!--
            v-model="form.name" — two-way binding: updates form.name on every keystroke.
            class="w-full" — PrimeVue InputText supports Tailwind classes directly.
        -->
        <InputText v-model="form.name" class="w-full" placeholder="e.g. Electronics" />

        <!-- form.errors.name is populated by Inertia after a failed server validation -->
        <small v-if="form.errors.name" class="text-red-500 mt-1 block">
            {{ form.errors.name }}
        </small>
    </div>

    <!-- Description — optional, nullable in DB and validation rules -->
    <div class="mb-4">
        <label class="block mb-2 font-medium text-gray-700 dark:text-gray-200">Description</label>
        <Textarea v-model="form.description" rows="4" class="w-full" placeholder="Optional description..." />
    </div>

    <!-- Image upload with live preview -->
    <div class="mb-4">
        <label class="block mb-2 font-medium text-gray-700 dark:text-gray-200">Image</label>

        <!--
            FileUpload (mode="basic") renders a single "Choose Image" button.
            :auto="false" → does NOT upload immediately on selection — we upload with the form.
            accept="image/*" → browser file picker filter (MIME validation is on the server too).
            @select="onImageSelect" → our handler stores the File and creates a preview URL.
        -->
        <FileUpload
            mode="basic"
            accept="image/*"
            :auto="false"
            chooseLabel="Choose Image"
            @select="onImageSelect"
        />

        <!--
            v-if="preview" — only show the preview img when a URL exists.
            On Create: preview is null until a file is selected.
            On Edit: preview starts as the existing image URL from CategoryResource.
        -->
        <div v-if="preview" class="mt-3">
            <img :src="preview" class="h-32 rounded shadow object-cover" alt="Category preview" />
        </div>

        <small v-if="form.errors.image" class="text-red-500 mt-1 block">
            {{ form.errors.image }}
        </small>
    </div>

    <!-- Status toggle — active (true) shows category on storefront, inactive (false) hides it -->
    <div class="mb-6 flex items-center gap-3">
        <!--
            InputSwitch is PrimeVue's toggle switch — binds to a boolean.
            v-model="form.status" sends 1 (true) or 0 (false) to Laravel.
            Laravel's `boolean` validation rule accepts true/false/1/0.
        -->
        <InputSwitch v-model="form.status" />
        <span class="text-gray-700 dark:text-gray-200">Active</span>
    </div>

    <!--
        :loading="form.processing" disables the button and shows a spinner while
        the XHR request is in-flight — prevents double submissions.
    -->
    <Button
        label="Save Category"
        icon="pi pi-check"
        :loading="form.processing"
        @click="submit"
    />
</div>
</template>
