<?php

declare(strict_types=1);

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

/**
 * BrandRequest — validates both store and update for the Brand resource.
 *
 * WHY one class for both actions?
 *  - The slug is auto-generated by Spatie HasSlug (never submitted by the form),
 *    so there is no unique-ignore-current-id conflict between store and update.
 *  - If you ever expose a manual slug field, split into BrandStoreRequest +
 *    BrandUpdateRequest and add Rule::unique()->ignore($brand->id) on update.
 */
class BrandRequest extends FormRequest
{
    /**
     * Admin routes are guarded by `auth` + `role:admin` middleware.
     * Any request reaching here is already authenticated and authorised.
     */
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            // `name` drives slug auto-generation — required and must be unique among active brands.
            'name' => ['required', 'string', 'max:255'],

            // Brand logo — optional. `image` rule validates MIME type (jpeg/png/gif/webp),
            // not just the file extension. 2 MB cap prevents memory exhaustion.
            'image' => ['nullable', 'image', 'max:2048'],

            // Active/inactive toggle. The `boolean` rule accepts true, false, 1, 0, "1", "0".
            'status' => ['boolean'],
        ];
    }
}
