<?php

declare(strict_types=1);

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Validates both store and update requests for the Category resource.
 *
 * WHY one class for both store and update?
 *  - The validation rules are identical for both actions — the slug is NOT submitted
 *    by the form (it's auto-generated by Spatie HasSlug on the model), so there is
 *    no unique-ignore-current-id problem.
 *  - If you ever add a manual `slug` field to the form, split this into
 *    CategoryStoreRequest + CategoryUpdateRequest and add Rule::unique()->ignore($id).
 */
class CategoryRequest extends FormRequest
{
    /**
     * Admin routes are protected by `auth` + `role:admin` middleware.
     * Any request that reaches here is already authenticated and authorised.
     */
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            // `name` is required — it drives the auto-slug and is the primary identifier.
            'name' => ['required', 'string', 'max:255'],

            // `description` is optional marketing copy — nullable keeps NULL in the DB
            // instead of an empty string, which is easier to check with `whereNull()`.
            'description' => ['nullable', 'string'],

            // `image` is optional — categories can exist without a cover image.
            // `image` rule checks MIME type (jpeg/png/gif/webp), not just extension.
            // `max:2048` = 2 MB — prevents large uploads exhausting disk or memory.
            'image' => ['nullable', 'image', 'max:2048'],

            // `status` is a boolean toggle (active / inactive).
            // The `boolean` rule accepts true, false, 1, 0, "1", "0" — covers checkbox inputs.
            'status' => ['boolean'],
        ];
    }
}
